services:
  runner:
    image: ghcr.io/zevszym/craftbe-e2e-runner:latest
    # build: .  # uncomment for local builds
    env_file: .env
    environment:
      - RUNNER_NAME=${RUNNER_NAME:-craftbe-runner}
    restart: always
    security_opt:
      - seccomp=unconfined  # needed for Chromium sandbox
